language: rust

addons:
  apt:
    packages:
    - gcc
    - g++
    - libleveldb-dev
    - libssl-dev

rust:
- stable

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.local
  - $TRAVIS_BUILD_DIR/target
  - $TRAVIS_BUILD_DIR/sandbox_tests/target
sudo: false

env:
  global:
  - CLIPPY_VERS=0.0.155
  - RUSTFMT_VERS=0.9.0

install:
- |
  if [ ! -f "$HOME/.local/lib/libsodium.a" ]; then
    wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.13.tar.gz
    tar xvf libsodium-1.0.13.tar.gz
    cd libsodium-1.0.13
    ./configure --prefix=$HOME/.local
    make
    make install
    cd ..
  fi
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig
- |
  if [[ "$FEATURE" == "clippy" ]]; then
    cargo clippy --version | grep $CLIPPY_VERS || cargo install clippy --force --vers $CLIPPY_VERS
  fi
- |
  if [[ "$FEATURE" == "fmt" ]]; then
    cargo-audit -V || cargo install cargo-audit --force
    rustfmt -V | grep $RUSTFMT_VERS || cargo install rustfmt --vers $RUSTFMT_VERS --force
    cargo update
  fi
- cargo install --list

script: skip

jobs:
  include:
  - stage: lint
    env:
    - FEATURE=fmt
    script:
    - cargo audit
    - cargo fmt -p exonum-configuration -- --write-mode=diff
    - cd sandbox_tests && cargo fmt -p exonum-configuration-sandbox -- --write-mode=diff
  - stage: lint
    rust: nightly-2017-08-31
    env:
    - FEATURE=clippy
    script:
    - cargo clippy -- -D warnings
  - stage: lint
    rust: nightly-2017-08-31
    env:
    - FEATURE=clippy
    # Needed to distinguish among `clippy` jobs when creating caches;
    # see https://docs.travis-ci.com/user/caching#Caches-and-build-matrices
    - SANDBOX=1
    script:
    - cd sandbox_tests && cargo clippy -- -D warnings
  - stage: test
    script:
    - cargo build
    - cargo run --example configuration
    - cargo test
    - RUST_LOG=off cargo test --manifest-path sandbox_tests/Cargo.toml

notifications:
  slack:
    secure: FnDaD3+0m3+XqQmakHZF9zMvtXhRQczP8qoiAS471JFWpBQyXbp+v98K7dIyRAlqwiAFaJuTr8Zxsem8bzmBoUixML0AN2ekngI1S147LMITMov6PEuruxQHfaWjCJ2L8iZy6vUQH+afZcJmEVMhCVJijgFpHyngBcDrCxFg5QJXwWTXztWxQlcoyCz1U4E3EuJWm2w/8MZwRsD4L5RlwrfBpc7tVeETekhakR0iDYjn5mt0AD+lpBfHcppB3LE5JTIc7nQR4OmmWZ9JJbp6qbFcqn7WEUQsubJuAfSRVwosTZxjd0lPiK9gw8F7RaYvemV4A7Wmc7WNthDKkf7XZ79wMTrBvB2FnozZXvCnwTBrm/KadZtnv9F1Hof4a7F3p+F29RY+FV6AJGI4xtSZYRKFnUCUgmKxlZUYtQ9E8ToZsn/ZgsilVL3RWCnIF1PJW8nnQiT5b9QbyT9z1hDqifeloBW0WJDxCMGz/jKDNx9kiRdnytcXOFy/2koDbXtrIUchPmMdunpMGB0qk8LUgnmV1v7dWcBQlGWrg+OwdyUQqBdaLmKHAqQ9quK4EUxIolxoT+AN0prquuoRMY8uCVZ/LpaGMWKofoDoj9m12/uGxDJOAXZJ2dGhr/672mwvG+qX40JcF24aRAZaw5pQ4GLVUdtIuRy6TjgMEomqP64=
